#!/usr/bin/env php
<?php

require __DIR__ . '/../config/config.php';
require __DIR__ . '/../app/Core/Database.php';
require __DIR__ . '/../app/Core/AdminSeeder.php';

use App\Core\AdminSeeder;

AdminSeeder::seed();
